# Generated by Django 2.0.4 on 2018-05-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180529_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('time', models.DateField()),
                ('event', models.CharField(max_length=100)),
            ],
        ),
    ]
