# Generated by Django 2.0.4 on 2018-06-03 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180603_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 3, 11, 34, 33, 241375, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 3, 11, 34, 33, 240861, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 3, 11, 34, 33, 240305, tzinfo=utc)),
        ),
    ]
