# Generated by Django 2.0.4 on 2018-05-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='event',
            field=models.CharField(default='test event', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
