# Generated by Django 2.0.4 on 2018-05-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180530_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='event',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='time',
        ),
    ]
