# Generated by Django 2.0.4 on 2018-05-30 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180530_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='event',
            field=models.CharField(default='test event', max_length=100),
        ),
        migrations.AddField(
            model_name='purchase',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
