# Generated by Django 2.0.4 on 2018-06-03 15:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180603_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 3, 15, 17, 44, 773299, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 3, 15, 17, 44, 772675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 3, 15, 17, 44, 771899, tzinfo=utc)),
        ),
    ]
