# Generated by Django 2.0.4 on 2018-05-30 08:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180530_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 30, 8, 47, 37, 170939, tzinfo=utc)),
        ),
    ]
