# Generated by Django 2.0.4 on 2018-05-30 09:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180530_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 30, 9, 8, 26, 691402, tzinfo=utc)),
        ),
    ]
