# Generated by Django 2.0.4 on 2018-05-30 15:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180530_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='enkeltsalg', max_length=200)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2018, 5, 30, 15, 33, 50, 485278, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='purchase',
            name='event',
            field=models.CharField(default='enkeltsalg', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 30, 15, 33, 50, 484687, tzinfo=utc)),
        ),
    ]
