# Generated by Django 2.0.4 on 2018-06-02 11:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180530_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.ImageField(upload_to='graphs/')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 2, 11, 58, 45, 647968, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='Enkeltsalg', max_length=200),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='event',
            field=models.CharField(default='Enkeltsalg', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 2, 11, 58, 45, 647252, tzinfo=utc)),
        ),
    ]
